/* 
 * Misty API
 *
 * Misty Open API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing DefaultApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class DefaultApiTests
    {
        private DefaultApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new DefaultApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DefaultApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' DefaultApi
            //Assert.IsInstanceOf(typeof(DefaultApi), instance);
        }

        
        /// <summary>
        /// Test Drive
        /// </summary>
        [Test]
        public void DriveTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Object linearVelocity = null;
            //Object angularVelocity = null;
            //InlineObject inlineObject = null;
            //var response = instance.Drive(linearVelocity, angularVelocity, inlineObject);
            //Assert.IsInstanceOf(typeof(List<InlineResponse200>), response, "response is List<InlineResponse200>");
        }
        
        /// <summary>
        /// Test DriveHeading
        /// </summary>
        [Test]
        public void DriveHeadingTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Object heading = null;
            //Object distance = null;
            //Object timeMS = null;
            //InlineObject2 inlineObject2 = null;
            //var response = instance.DriveHeading(heading, distance, timeMS, inlineObject2);
            //Assert.IsInstanceOf(typeof(List<InlineResponse2001>), response, "response is List<InlineResponse2001>");
        }
        
        /// <summary>
        /// Test DriveTime
        /// </summary>
        [Test]
        public void DriveTimeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Object linearVelocity = null;
            //Object angularVelocity = null;
            //Object timeMS = null;
            //InlineObject3 inlineObject3 = null;
            //var response = instance.DriveTime(linearVelocity, angularVelocity, timeMS, inlineObject3);
            //Assert.IsInstanceOf(typeof(List<InlineResponse200>), response, "response is List<InlineResponse200>");
        }
        
        /// <summary>
        /// Test DriveTrack
        /// </summary>
        [Test]
        public void DriveTrackTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Object rightTrackSpeed = null;
            //Object leftTrackSpeed = null;
            //InlineObject1 inlineObject1 = null;
            //var response = instance.DriveTrack(rightTrackSpeed, leftTrackSpeed, inlineObject1);
            //Assert.IsInstanceOf(typeof(List<InlineResponse200>), response, "response is List<InlineResponse200>");
        }
        
        /// <summary>
        /// Test GetDeviceInformation
        /// </summary>
        [Test]
        public void GetDeviceInformationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetDeviceInformation();
            //Assert.IsInstanceOf(typeof(List<InlineResponse2001>), response, "response is List<InlineResponse2001>");
        }
        
        /// <summary>
        /// Test Stop
        /// </summary>
        [Test]
        public void StopTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.Stop();
            //Assert.IsInstanceOf(typeof(List<InlineResponse200>), response, "response is List<InlineResponse200>");
        }
        
    }

}
