/*
 * Misty API
 *
 * Misty Open API
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineObject1 struct for InlineObject1
type InlineObject1 struct {
	RightTrackSpeed float32 `json:"RightTrackSpeed,omitempty"`
	LeftTrackSpeed float32 `json:"LeftTrackSpeed,omitempty"`
}
