/*
 * Misty API
 *
 * Misty Open API
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse2001 struct for InlineResponse2001
type InlineResponse2001 struct {
	Result ApiDeviceResult `json:"result,omitempty"`
	Status map[string]interface{} `json:"status,omitempty"`
}
