/*
 * Misty API
 *
 * Misty Open API
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineObject struct for InlineObject
type InlineObject struct {
	LinearVelocity float32 `json:"LinearVelocity,omitempty"`
	AngularVelocity float32 `json:"AngularVelocity,omitempty"`
}
