/*
 * Misty API
 *
 * Misty Open API
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineObject2 struct for InlineObject2
type InlineObject2 struct {
	Heading map[string]interface{} `json:"Heading,omitempty"`
	Distance map[string]interface{} `json:"Distance,omitempty"`
	TimeMS map[string]interface{} `json:"TimeMS,omitempty"`
}
