/*
 * Misty API
 *
 * Misty Open API
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineObject1 struct for InlineObject1
type InlineObject1 struct {
	RightTrackSpeed map[string]interface{} `json:"RightTrackSpeed,omitempty"`
	LeftTrackSpeed map[string]interface{} `json:"LeftTrackSpeed,omitempty"`
}
