/*
 * Misty API
 *
 * Misty Open API
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineObject3 struct for InlineObject3
type InlineObject3 struct {
	LinearVelocity map[string]interface{} `json:"LinearVelocity,omitempty"`
	AngularVelocity map[string]interface{} `json:"AngularVelocity,omitempty"`
	TimeMS map[string]interface{} `json:"TimeMS,omitempty"`
}
