/*
 * Misty API
 * Misty Open API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ApiDeviceResult
 */
public class ApiDeviceResultTest {
    private final ApiDeviceResult model = new ApiDeviceResult();

    /**
     * Model tests for ApiDeviceResult
     */
    @Test
    public void testApiDeviceResult() {
        // TODO: test ApiDeviceResult
    }

    /**
     * Test the property 'robotId'
     */
    @Test
    public void robotIdTest() {
        // TODO: test robotId
    }

    /**
     * Test the property 'serialNumber'
     */
    @Test
    public void serialNumberTest() {
        // TODO: test serialNumber
    }

    /**
     * Test the property 'currentProfileName'
     */
    @Test
    public void currentProfileNameTest() {
        // TODO: test currentProfileName
    }

    /**
     * Test the property 'hardwareInfo'
     */
    @Test
    public void hardwareInfoTest() {
        // TODO: test hardwareInfo
    }

    /**
     * Test the property 'ipAddress'
     */
    @Test
    public void ipAddressTest() {
        // TODO: test ipAddress
    }

    /**
     * Test the property 'batteryLevel'
     */
    @Test
    public void batteryLevelTest() {
        // TODO: test batteryLevel
    }

    /**
     * Test the property 'occipitalDeviceInfo'
     */
    @Test
    public void occipitalDeviceInfoTest() {
        // TODO: test occipitalDeviceInfo
    }

    /**
     * Test the property 'outputCapabilities'
     */
    @Test
    public void outputCapabilitiesTest() {
        // TODO: test outputCapabilities
    }

    /**
     * Test the property 'robotVersion'
     */
    @Test
    public void robotVersionTest() {
        // TODO: test robotVersion
    }

    /**
     * Test the property 'sensoryServiceAppVersion'
     */
    @Test
    public void sensoryServiceAppVersionTest() {
        // TODO: test sensoryServiceAppVersion
    }

    /**
     * Test the property 'windowsOSVersion'
     */
    @Test
    public void windowsOSVersionTest() {
        // TODO: test windowsOSVersion
    }

    /**
     * Test the property 'sensorCapabilities'
     */
    @Test
    public void sensorCapabilitiesTest() {
        // TODO: test sensorCapabilities
    }

}
