/*
 * Misty API
 * Misty Open API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for InlineObject2
 */
public class InlineObject2Test {
    private final InlineObject2 model = new InlineObject2();

    /**
     * Model tests for InlineObject2
     */
    @Test
    public void testInlineObject2() {
        // TODO: test InlineObject2
    }

    /**
     * Test the property 'heading'
     */
    @Test
    public void headingTest() {
        // TODO: test heading
    }

    /**
     * Test the property 'distance'
     */
    @Test
    public void distanceTest() {
        // TODO: test distance
    }

    /**
     * Test the property 'timeMS'
     */
    @Test
    public void timeMSTest() {
        // TODO: test timeMS
    }

}
