/*
 * Misty API
 * Misty Open API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for InlineObject3
 */
public class InlineObject3Test {
    private final InlineObject3 model = new InlineObject3();

    /**
     * Model tests for InlineObject3
     */
    @Test
    public void testInlineObject3() {
        // TODO: test InlineObject3
    }

    /**
     * Test the property 'linearVelocity'
     */
    @Test
    public void linearVelocityTest() {
        // TODO: test linearVelocity
    }

    /**
     * Test the property 'angularVelocity'
     */
    @Test
    public void angularVelocityTest() {
        // TODO: test angularVelocity
    }

    /**
     * Test the property 'timeMS'
     */
    @Test
    public void timeMSTest() {
        // TODO: test timeMS
    }

}
