/*
 * Misty API
 * Misty Open API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ApiDeviceResult
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-11-19T08:56:35.369959-07:00[America/Denver]")
public class ApiDeviceResult {
  public static final String SERIALIZED_NAME_ROBOT_ID = "robotId";
  @SerializedName(SERIALIZED_NAME_ROBOT_ID)
  private Object robotId = null;

  public static final String SERIALIZED_NAME_SERIAL_NUMBER = "serialNumber";
  @SerializedName(SERIALIZED_NAME_SERIAL_NUMBER)
  private Object serialNumber = null;

  public static final String SERIALIZED_NAME_CURRENT_PROFILE_NAME = "currentProfileName";
  @SerializedName(SERIALIZED_NAME_CURRENT_PROFILE_NAME)
  private Object currentProfileName = null;

  public static final String SERIALIZED_NAME_HARDWARE_INFO = "hardwareInfo";
  @SerializedName(SERIALIZED_NAME_HARDWARE_INFO)
  private Object hardwareInfo;

  public static final String SERIALIZED_NAME_IP_ADDRESS = "ipAddress";
  @SerializedName(SERIALIZED_NAME_IP_ADDRESS)
  private Object ipAddress = null;

  public static final String SERIALIZED_NAME_BATTERY_LEVEL = "batteryLevel";
  @SerializedName(SERIALIZED_NAME_BATTERY_LEVEL)
  private Object batteryLevel = null;

  public static final String SERIALIZED_NAME_OCCIPITAL_DEVICE_INFO = "occipitalDeviceInfo";
  @SerializedName(SERIALIZED_NAME_OCCIPITAL_DEVICE_INFO)
  private Object occipitalDeviceInfo;

  public static final String SERIALIZED_NAME_OUTPUT_CAPABILITIES = "outputCapabilities";
  @SerializedName(SERIALIZED_NAME_OUTPUT_CAPABILITIES)
  private List<Object> outputCapabilities = null;

  public static final String SERIALIZED_NAME_ROBOT_VERSION = "robotVersion";
  @SerializedName(SERIALIZED_NAME_ROBOT_VERSION)
  private Object robotVersion = null;

  public static final String SERIALIZED_NAME_SENSORY_SERVICE_APP_VERSION = "sensoryServiceAppVersion";
  @SerializedName(SERIALIZED_NAME_SENSORY_SERVICE_APP_VERSION)
  private Object sensoryServiceAppVersion = null;

  public static final String SERIALIZED_NAME_WINDOWS_O_S_VERSION = "windowsOSVersion";
  @SerializedName(SERIALIZED_NAME_WINDOWS_O_S_VERSION)
  private Object windowsOSVersion = null;

  public static final String SERIALIZED_NAME_SENSOR_CAPABILITIES = "sensorCapabilities";
  @SerializedName(SERIALIZED_NAME_SENSOR_CAPABILITIES)
  private List<Object> sensorCapabilities = null;


  public ApiDeviceResult robotId(Object robotId) {
    
    this.robotId = robotId;
    return this;
  }

   /**
   * Get robotId
   * @return robotId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getRobotId() {
    return robotId;
  }


  public void setRobotId(Object robotId) {
    this.robotId = robotId;
  }


  public ApiDeviceResult serialNumber(Object serialNumber) {
    
    this.serialNumber = serialNumber;
    return this;
  }

   /**
   * Get serialNumber
   * @return serialNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getSerialNumber() {
    return serialNumber;
  }


  public void setSerialNumber(Object serialNumber) {
    this.serialNumber = serialNumber;
  }


  public ApiDeviceResult currentProfileName(Object currentProfileName) {
    
    this.currentProfileName = currentProfileName;
    return this;
  }

   /**
   * Get currentProfileName
   * @return currentProfileName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getCurrentProfileName() {
    return currentProfileName;
  }


  public void setCurrentProfileName(Object currentProfileName) {
    this.currentProfileName = currentProfileName;
  }


  public ApiDeviceResult hardwareInfo(Object hardwareInfo) {
    
    this.hardwareInfo = hardwareInfo;
    return this;
  }

   /**
   * Get hardwareInfo
   * @return hardwareInfo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getHardwareInfo() {
    return hardwareInfo;
  }


  public void setHardwareInfo(Object hardwareInfo) {
    this.hardwareInfo = hardwareInfo;
  }


  public ApiDeviceResult ipAddress(Object ipAddress) {
    
    this.ipAddress = ipAddress;
    return this;
  }

   /**
   * Get ipAddress
   * @return ipAddress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getIpAddress() {
    return ipAddress;
  }


  public void setIpAddress(Object ipAddress) {
    this.ipAddress = ipAddress;
  }


  public ApiDeviceResult batteryLevel(Object batteryLevel) {
    
    this.batteryLevel = batteryLevel;
    return this;
  }

   /**
   * Get batteryLevel
   * @return batteryLevel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getBatteryLevel() {
    return batteryLevel;
  }


  public void setBatteryLevel(Object batteryLevel) {
    this.batteryLevel = batteryLevel;
  }


  public ApiDeviceResult occipitalDeviceInfo(Object occipitalDeviceInfo) {
    
    this.occipitalDeviceInfo = occipitalDeviceInfo;
    return this;
  }

   /**
   * Get occipitalDeviceInfo
   * @return occipitalDeviceInfo
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getOccipitalDeviceInfo() {
    return occipitalDeviceInfo;
  }


  public void setOccipitalDeviceInfo(Object occipitalDeviceInfo) {
    this.occipitalDeviceInfo = occipitalDeviceInfo;
  }


  public ApiDeviceResult outputCapabilities(List<Object> outputCapabilities) {
    
    this.outputCapabilities = outputCapabilities;
    return this;
  }

  public ApiDeviceResult addOutputCapabilitiesItem(Object outputCapabilitiesItem) {
    if (this.outputCapabilities == null) {
      this.outputCapabilities = new ArrayList<Object>();
    }
    this.outputCapabilities.add(outputCapabilitiesItem);
    return this;
  }

   /**
   * Get outputCapabilities
   * @return outputCapabilities
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Object> getOutputCapabilities() {
    return outputCapabilities;
  }


  public void setOutputCapabilities(List<Object> outputCapabilities) {
    this.outputCapabilities = outputCapabilities;
  }


  public ApiDeviceResult robotVersion(Object robotVersion) {
    
    this.robotVersion = robotVersion;
    return this;
  }

   /**
   * Get robotVersion
   * @return robotVersion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getRobotVersion() {
    return robotVersion;
  }


  public void setRobotVersion(Object robotVersion) {
    this.robotVersion = robotVersion;
  }


  public ApiDeviceResult sensoryServiceAppVersion(Object sensoryServiceAppVersion) {
    
    this.sensoryServiceAppVersion = sensoryServiceAppVersion;
    return this;
  }

   /**
   * Get sensoryServiceAppVersion
   * @return sensoryServiceAppVersion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getSensoryServiceAppVersion() {
    return sensoryServiceAppVersion;
  }


  public void setSensoryServiceAppVersion(Object sensoryServiceAppVersion) {
    this.sensoryServiceAppVersion = sensoryServiceAppVersion;
  }


  public ApiDeviceResult windowsOSVersion(Object windowsOSVersion) {
    
    this.windowsOSVersion = windowsOSVersion;
    return this;
  }

   /**
   * Get windowsOSVersion
   * @return windowsOSVersion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getWindowsOSVersion() {
    return windowsOSVersion;
  }


  public void setWindowsOSVersion(Object windowsOSVersion) {
    this.windowsOSVersion = windowsOSVersion;
  }


  public ApiDeviceResult sensorCapabilities(List<Object> sensorCapabilities) {
    
    this.sensorCapabilities = sensorCapabilities;
    return this;
  }

  public ApiDeviceResult addSensorCapabilitiesItem(Object sensorCapabilitiesItem) {
    if (this.sensorCapabilities == null) {
      this.sensorCapabilities = new ArrayList<Object>();
    }
    this.sensorCapabilities.add(sensorCapabilitiesItem);
    return this;
  }

   /**
   * Get sensorCapabilities
   * @return sensorCapabilities
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Object> getSensorCapabilities() {
    return sensorCapabilities;
  }


  public void setSensorCapabilities(List<Object> sensorCapabilities) {
    this.sensorCapabilities = sensorCapabilities;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiDeviceResult apiDeviceResult = (ApiDeviceResult) o;
    return Objects.equals(this.robotId, apiDeviceResult.robotId) &&
        Objects.equals(this.serialNumber, apiDeviceResult.serialNumber) &&
        Objects.equals(this.currentProfileName, apiDeviceResult.currentProfileName) &&
        Objects.equals(this.hardwareInfo, apiDeviceResult.hardwareInfo) &&
        Objects.equals(this.ipAddress, apiDeviceResult.ipAddress) &&
        Objects.equals(this.batteryLevel, apiDeviceResult.batteryLevel) &&
        Objects.equals(this.occipitalDeviceInfo, apiDeviceResult.occipitalDeviceInfo) &&
        Objects.equals(this.outputCapabilities, apiDeviceResult.outputCapabilities) &&
        Objects.equals(this.robotVersion, apiDeviceResult.robotVersion) &&
        Objects.equals(this.sensoryServiceAppVersion, apiDeviceResult.sensoryServiceAppVersion) &&
        Objects.equals(this.windowsOSVersion, apiDeviceResult.windowsOSVersion) &&
        Objects.equals(this.sensorCapabilities, apiDeviceResult.sensorCapabilities);
  }

  @Override
  public int hashCode() {
    return Objects.hash(robotId, serialNumber, currentProfileName, hardwareInfo, ipAddress, batteryLevel, occipitalDeviceInfo, outputCapabilities, robotVersion, sensoryServiceAppVersion, windowsOSVersion, sensorCapabilities);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiDeviceResult {\n");
    sb.append("    robotId: ").append(toIndentedString(robotId)).append("\n");
    sb.append("    serialNumber: ").append(toIndentedString(serialNumber)).append("\n");
    sb.append("    currentProfileName: ").append(toIndentedString(currentProfileName)).append("\n");
    sb.append("    hardwareInfo: ").append(toIndentedString(hardwareInfo)).append("\n");
    sb.append("    ipAddress: ").append(toIndentedString(ipAddress)).append("\n");
    sb.append("    batteryLevel: ").append(toIndentedString(batteryLevel)).append("\n");
    sb.append("    occipitalDeviceInfo: ").append(toIndentedString(occipitalDeviceInfo)).append("\n");
    sb.append("    outputCapabilities: ").append(toIndentedString(outputCapabilities)).append("\n");
    sb.append("    robotVersion: ").append(toIndentedString(robotVersion)).append("\n");
    sb.append("    sensoryServiceAppVersion: ").append(toIndentedString(sensoryServiceAppVersion)).append("\n");
    sb.append("    windowsOSVersion: ").append(toIndentedString(windowsOSVersion)).append("\n");
    sb.append("    sensorCapabilities: ").append(toIndentedString(sensorCapabilities)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

