/*
 * Misty API
 * Misty Open API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * InlineObject3
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-11-19T08:56:35.369959-07:00[America/Denver]")
public class InlineObject3 {
  public static final String SERIALIZED_NAME_LINEAR_VELOCITY = "LinearVelocity";
  @SerializedName(SERIALIZED_NAME_LINEAR_VELOCITY)
  private Object linearVelocity = null;

  public static final String SERIALIZED_NAME_ANGULAR_VELOCITY = "AngularVelocity";
  @SerializedName(SERIALIZED_NAME_ANGULAR_VELOCITY)
  private Object angularVelocity = null;

  public static final String SERIALIZED_NAME_TIME_M_S = "TimeMS";
  @SerializedName(SERIALIZED_NAME_TIME_M_S)
  private Object timeMS = null;


  public InlineObject3 linearVelocity(Object linearVelocity) {
    
    this.linearVelocity = linearVelocity;
    return this;
  }

   /**
   * Get linearVelocity
   * @return linearVelocity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getLinearVelocity() {
    return linearVelocity;
  }


  public void setLinearVelocity(Object linearVelocity) {
    this.linearVelocity = linearVelocity;
  }


  public InlineObject3 angularVelocity(Object angularVelocity) {
    
    this.angularVelocity = angularVelocity;
    return this;
  }

   /**
   * Get angularVelocity
   * @return angularVelocity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getAngularVelocity() {
    return angularVelocity;
  }


  public void setAngularVelocity(Object angularVelocity) {
    this.angularVelocity = angularVelocity;
  }


  public InlineObject3 timeMS(Object timeMS) {
    
    this.timeMS = timeMS;
    return this;
  }

   /**
   * Get timeMS
   * @return timeMS
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getTimeMS() {
    return timeMS;
  }


  public void setTimeMS(Object timeMS) {
    this.timeMS = timeMS;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineObject3 inlineObject3 = (InlineObject3) o;
    return Objects.equals(this.linearVelocity, inlineObject3.linearVelocity) &&
        Objects.equals(this.angularVelocity, inlineObject3.angularVelocity) &&
        Objects.equals(this.timeMS, inlineObject3.timeMS);
  }

  @Override
  public int hashCode() {
    return Objects.hash(linearVelocity, angularVelocity, timeMS);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineObject3 {\n");
    sb.append("    linearVelocity: ").append(toIndentedString(linearVelocity)).append("\n");
    sb.append("    angularVelocity: ").append(toIndentedString(angularVelocity)).append("\n");
    sb.append("    timeMS: ").append(toIndentedString(timeMS)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

