/*
 * Misty API
 * Misty Open API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * InlineObject2
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-11-19T08:56:35.369959-07:00[America/Denver]")
public class InlineObject2 {
  public static final String SERIALIZED_NAME_HEADING = "Heading";
  @SerializedName(SERIALIZED_NAME_HEADING)
  private Object heading = null;

  public static final String SERIALIZED_NAME_DISTANCE = "Distance";
  @SerializedName(SERIALIZED_NAME_DISTANCE)
  private Object distance = null;

  public static final String SERIALIZED_NAME_TIME_M_S = "TimeMS";
  @SerializedName(SERIALIZED_NAME_TIME_M_S)
  private Object timeMS = null;


  public InlineObject2 heading(Object heading) {
    
    this.heading = heading;
    return this;
  }

   /**
   * Get heading
   * @return heading
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getHeading() {
    return heading;
  }


  public void setHeading(Object heading) {
    this.heading = heading;
  }


  public InlineObject2 distance(Object distance) {
    
    this.distance = distance;
    return this;
  }

   /**
   * Get distance
   * @return distance
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getDistance() {
    return distance;
  }


  public void setDistance(Object distance) {
    this.distance = distance;
  }


  public InlineObject2 timeMS(Object timeMS) {
    
    this.timeMS = timeMS;
    return this;
  }

   /**
   * Get timeMS
   * @return timeMS
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getTimeMS() {
    return timeMS;
  }


  public void setTimeMS(Object timeMS) {
    this.timeMS = timeMS;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineObject2 inlineObject2 = (InlineObject2) o;
    return Objects.equals(this.heading, inlineObject2.heading) &&
        Objects.equals(this.distance, inlineObject2.distance) &&
        Objects.equals(this.timeMS, inlineObject2.timeMS);
  }

  @Override
  public int hashCode() {
    return Objects.hash(heading, distance, timeMS);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineObject2 {\n");
    sb.append("    heading: ").append(toIndentedString(heading)).append("\n");
    sb.append("    distance: ").append(toIndentedString(distance)).append("\n");
    sb.append("    timeMS: ").append(toIndentedString(timeMS)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

