/*
 * Misty API
 * Misty Open API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * InlineObject1
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-11-19T08:56:35.369959-07:00[America/Denver]")
public class InlineObject1 {
  public static final String SERIALIZED_NAME_RIGHT_TRACK_SPEED = "RightTrackSpeed";
  @SerializedName(SERIALIZED_NAME_RIGHT_TRACK_SPEED)
  private Object rightTrackSpeed = null;

  public static final String SERIALIZED_NAME_LEFT_TRACK_SPEED = "LeftTrackSpeed";
  @SerializedName(SERIALIZED_NAME_LEFT_TRACK_SPEED)
  private Object leftTrackSpeed = null;


  public InlineObject1 rightTrackSpeed(Object rightTrackSpeed) {
    
    this.rightTrackSpeed = rightTrackSpeed;
    return this;
  }

   /**
   * Get rightTrackSpeed
   * @return rightTrackSpeed
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getRightTrackSpeed() {
    return rightTrackSpeed;
  }


  public void setRightTrackSpeed(Object rightTrackSpeed) {
    this.rightTrackSpeed = rightTrackSpeed;
  }


  public InlineObject1 leftTrackSpeed(Object leftTrackSpeed) {
    
    this.leftTrackSpeed = leftTrackSpeed;
    return this;
  }

   /**
   * Get leftTrackSpeed
   * @return leftTrackSpeed
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getLeftTrackSpeed() {
    return leftTrackSpeed;
  }


  public void setLeftTrackSpeed(Object leftTrackSpeed) {
    this.leftTrackSpeed = leftTrackSpeed;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineObject1 inlineObject1 = (InlineObject1) o;
    return Objects.equals(this.rightTrackSpeed, inlineObject1.rightTrackSpeed) &&
        Objects.equals(this.leftTrackSpeed, inlineObject1.leftTrackSpeed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rightTrackSpeed, leftTrackSpeed);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineObject1 {\n");
    sb.append("    rightTrackSpeed: ").append(toIndentedString(rightTrackSpeed)).append("\n");
    sb.append("    leftTrackSpeed: ").append(toIndentedString(leftTrackSpeed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

