/**
 * Misty API
 * Misty Open API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MistyApi);
  }
}(this, function(expect, MistyApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MistyApi.DefaultApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DefaultApi', function() {
    describe('drive', function() {
      it('should call drive successfully', function(done) {
        //uncomment below and update the code to test drive
        //instance.drive(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('driveGet', function() {
      it('should call driveGet successfully', function(done) {
        //uncomment below and update the code to test driveGet
        //instance.driveGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('driveTrack', function() {
      it('should call driveTrack successfully', function(done) {
        //uncomment below and update the code to test driveTrack
        //instance.driveTrack(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('driveTrackGet', function() {
      it('should call driveTrackGet successfully', function(done) {
        //uncomment below and update the code to test driveTrackGet
        //instance.driveTrackGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDeviceInformation', function() {
      it('should call getDeviceInformation successfully', function(done) {
        //uncomment below and update the code to test getDeviceInformation
        //instance.getDeviceInformation(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('stop', function() {
      it('should call stop successfully', function(done) {
        //uncomment below and update the code to test stop
        //instance.stop(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('stopGet', function() {
      it('should call stopGet successfully', function(done) {
        //uncomment below and update the code to test stopGet
        //instance.stopGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
