# coding: utf-8

"""
    Misty API

    Misty Open API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class InlineObject(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'linear_velocity': 'float',
        'angular_velocity': 'float'
    }

    attribute_map = {
        'linear_velocity': 'LinearVelocity',
        'angular_velocity': 'AngularVelocity'
    }

    def __init__(self, linear_velocity=None, angular_velocity=None, local_vars_configuration=None):  # noqa: E501
        """InlineObject - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._linear_velocity = None
        self._angular_velocity = None
        self.discriminator = None

        if linear_velocity is not None:
            self.linear_velocity = linear_velocity
        if angular_velocity is not None:
            self.angular_velocity = angular_velocity

    @property
    def linear_velocity(self):
        """Gets the linear_velocity of this InlineObject.  # noqa: E501


        :return: The linear_velocity of this InlineObject.  # noqa: E501
        :rtype: float
        """
        return self._linear_velocity

    @linear_velocity.setter
    def linear_velocity(self, linear_velocity):
        """Sets the linear_velocity of this InlineObject.


        :param linear_velocity: The linear_velocity of this InlineObject.  # noqa: E501
        :type: float
        """

        self._linear_velocity = linear_velocity

    @property
    def angular_velocity(self):
        """Gets the angular_velocity of this InlineObject.  # noqa: E501


        :return: The angular_velocity of this InlineObject.  # noqa: E501
        :rtype: float
        """
        return self._angular_velocity

    @angular_velocity.setter
    def angular_velocity(self, angular_velocity):
        """Sets the angular_velocity of this InlineObject.


        :param angular_velocity: The angular_velocity of this InlineObject.  # noqa: E501
        :type: float
        """

        self._angular_velocity = angular_velocity

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineObject):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineObject):
            return True

        return self.to_dict() != other.to_dict()
