# coding: utf-8

"""
    Misty API

    Misty Open API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class InlineObject1(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'right_track_speed': 'float',
        'left_track_speed': 'float'
    }

    attribute_map = {
        'right_track_speed': 'RightTrackSpeed',
        'left_track_speed': 'LeftTrackSpeed'
    }

    def __init__(self, right_track_speed=None, left_track_speed=None, local_vars_configuration=None):  # noqa: E501
        """InlineObject1 - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._right_track_speed = None
        self._left_track_speed = None
        self.discriminator = None

        if right_track_speed is not None:
            self.right_track_speed = right_track_speed
        if left_track_speed is not None:
            self.left_track_speed = left_track_speed

    @property
    def right_track_speed(self):
        """Gets the right_track_speed of this InlineObject1.  # noqa: E501


        :return: The right_track_speed of this InlineObject1.  # noqa: E501
        :rtype: float
        """
        return self._right_track_speed

    @right_track_speed.setter
    def right_track_speed(self, right_track_speed):
        """Sets the right_track_speed of this InlineObject1.


        :param right_track_speed: The right_track_speed of this InlineObject1.  # noqa: E501
        :type: float
        """

        self._right_track_speed = right_track_speed

    @property
    def left_track_speed(self):
        """Gets the left_track_speed of this InlineObject1.  # noqa: E501


        :return: The left_track_speed of this InlineObject1.  # noqa: E501
        :rtype: float
        """
        return self._left_track_speed

    @left_track_speed.setter
    def left_track_speed(self, left_track_speed):
        """Sets the left_track_speed of this InlineObject1.


        :param left_track_speed: The left_track_speed of this InlineObject1.  # noqa: E501
        :type: float
        """

        self._left_track_speed = left_track_speed

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineObject1):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineObject1):
            return True

        return self.to_dict() != other.to_dict()
