# coding: utf-8

"""
    Misty API

    Misty Open API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.default_api import DefaultApi  # noqa: E501
from openapi_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_drive(self):
        """Test case for drive

        Drive  # noqa: E501
        """
        pass

    def test_drive_heading(self):
        """Test case for drive_heading

        Drive Heading  # noqa: E501
        """
        pass

    def test_drive_time(self):
        """Test case for drive_time

        Drive Time  # noqa: E501
        """
        pass

    def test_drive_track(self):
        """Test case for drive_track

        Drive Track  # noqa: E501
        """
        pass

    def test_get_device_information(self):
        """Test case for get_device_information

        Get Device Information  # noqa: E501
        """
        pass

    def test_stop(self):
        """Test case for stop

        Stop  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
