# coding: utf-8

"""
    Misty API

    Misty Open API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.default_api import DefaultApi  # noqa: E501
from openapi_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_drive_get(self):
        """Test case for api_drive_get

        Your GET endpoint  # noqa: E501
        """
        pass

    def test_api_drive_post(self):
        """Test case for api_drive_post

        """
        pass

    def test_api_drive_stop_get(self):
        """Test case for api_drive_stop_get

        Your GET endpoint  # noqa: E501
        """
        pass

    def test_api_drive_stop_post(self):
        """Test case for api_drive_stop_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
