/**
 * Misty API
 * Misty Open API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApiDeviceResult model module.
 * @module model/ApiDeviceResult
 * @version 1.0
 */
class ApiDeviceResult {
    /**
     * Constructs a new <code>ApiDeviceResult</code>.
     * @alias module:model/ApiDeviceResult
     */
    constructor() { 
        
        ApiDeviceResult.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ApiDeviceResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ApiDeviceResult} obj Optional instance to populate.
     * @return {module:model/ApiDeviceResult} The populated <code>ApiDeviceResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiDeviceResult();

            if (data.hasOwnProperty('robotId')) {
                obj['robotId'] = ApiClient.convertToType(data['robotId'], Object);
            }
            if (data.hasOwnProperty('serialNumber')) {
                obj['serialNumber'] = ApiClient.convertToType(data['serialNumber'], Object);
            }
            if (data.hasOwnProperty('currentProfileName')) {
                obj['currentProfileName'] = ApiClient.convertToType(data['currentProfileName'], Object);
            }
            if (data.hasOwnProperty('hardwareInfo')) {
                obj['hardwareInfo'] = ApiClient.convertToType(data['hardwareInfo'], Object);
            }
            if (data.hasOwnProperty('ipAddress')) {
                obj['ipAddress'] = ApiClient.convertToType(data['ipAddress'], Object);
            }
            if (data.hasOwnProperty('batteryLevel')) {
                obj['batteryLevel'] = ApiClient.convertToType(data['batteryLevel'], Object);
            }
            if (data.hasOwnProperty('occipitalDeviceInfo')) {
                obj['occipitalDeviceInfo'] = ApiClient.convertToType(data['occipitalDeviceInfo'], Object);
            }
            if (data.hasOwnProperty('outputCapabilities')) {
                obj['outputCapabilities'] = ApiClient.convertToType(data['outputCapabilities'], [Object]);
            }
            if (data.hasOwnProperty('robotVersion')) {
                obj['robotVersion'] = ApiClient.convertToType(data['robotVersion'], Object);
            }
            if (data.hasOwnProperty('sensoryServiceAppVersion')) {
                obj['sensoryServiceAppVersion'] = ApiClient.convertToType(data['sensoryServiceAppVersion'], Object);
            }
            if (data.hasOwnProperty('windowsOSVersion')) {
                obj['windowsOSVersion'] = ApiClient.convertToType(data['windowsOSVersion'], Object);
            }
            if (data.hasOwnProperty('sensorCapabilities')) {
                obj['sensorCapabilities'] = ApiClient.convertToType(data['sensorCapabilities'], [Object]);
            }
        }
        return obj;
    }


}

/**
 * @member {Object} robotId
 */
ApiDeviceResult.prototype['robotId'] = undefined;

/**
 * @member {Object} serialNumber
 */
ApiDeviceResult.prototype['serialNumber'] = undefined;

/**
 * @member {Object} currentProfileName
 */
ApiDeviceResult.prototype['currentProfileName'] = undefined;

/**
 * @member {Object} hardwareInfo
 */
ApiDeviceResult.prototype['hardwareInfo'] = undefined;

/**
 * @member {Object} ipAddress
 */
ApiDeviceResult.prototype['ipAddress'] = undefined;

/**
 * @member {Object} batteryLevel
 */
ApiDeviceResult.prototype['batteryLevel'] = undefined;

/**
 * @member {Object} occipitalDeviceInfo
 */
ApiDeviceResult.prototype['occipitalDeviceInfo'] = undefined;

/**
 * @member {Array.<Object>} outputCapabilities
 */
ApiDeviceResult.prototype['outputCapabilities'] = undefined;

/**
 * @member {Object} robotVersion
 */
ApiDeviceResult.prototype['robotVersion'] = undefined;

/**
 * @member {Object} sensoryServiceAppVersion
 */
ApiDeviceResult.prototype['sensoryServiceAppVersion'] = undefined;

/**
 * @member {Object} windowsOSVersion
 */
ApiDeviceResult.prototype['windowsOSVersion'] = undefined;

/**
 * @member {Array.<Object>} sensorCapabilities
 */
ApiDeviceResult.prototype['sensorCapabilities'] = undefined;






export default ApiDeviceResult;

