openapi: 3.0.0
info:
  title: Misty API
  version: '1.0'
  description: Misty Open API
servers:
  - url: 'http://localhost:3000'
    description: misty
paths:
  /api/drive:
    post:
      x-openapi-router-controller: api
      summary: Drive
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                items:
                  type: object
                  properties:
                    result:
                      type: boolean
                    status:
                      type: string
                description: response
                x-examples:
                  example-1:
                    - result: true
                      status: Success
                type: array
                title: response
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                LinearVelocity: {}
                AngularVelocity: {}
            examples:
              example-1:
                value:
                  LinearVelocity: 5
                  AngularVelocity: 5
        description: Drive
      description: Drive
      operationId: drive
      parameters:
        - schema: {}
          in: query
          name: LinearVelocity
        - schema: {}
          in: query
          name: AngularVelocity
    parameters: []
  /api/drive/stop:
    post:
      x-openapi-router-controller: api
      summary: Stop
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                items:
                  type: object
                  properties:
                    result:
                      type: boolean
                    status:
                      type: string
                description: response
                x-examples:
                  example-1:
                    - result: true
                      status: Success
                type: array
                title: response
      description: Stop
      operationId: stop
  /api/device:
    get:
      x-openapi-router-controller: api
      summary: Get Device Information
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                items:
                  type: object
                  properties:
                    result:
                      type: object
                      properties:
                        robotId: {}
                        serialNumber: {}
                        currentProfileName: {}
                        hardwareInfo:
                          type: object
                        ipAddress: {}
                        batteryLevel: {}
                        occipitalDeviceInfo:
                          type: object
                        outputCapabilities:
                          type: array
                          items: {}
                        robotVersion: {}
                        sensoryServiceAppVersion: {}
                        windowsOSVersion: {}
                        sensorCapabilities:
                          type: array
                          items: {}
                    status: {}
                description: ''
                x-examples:
                  get-device-information-example:
                    - result:
                        robotId: '12345'
                        serialNumber: '12345'
                        batteryLevel: 0.5
                        hardwareInfo: {}
                        ipAddress: 0.0.0.0
                        occipitalDeviceInfo: {}
                        outputCapabilities:
                          - sure
                        robotVersion: 1.0.0.0
                        sensorCapabilities:
                          - uh hunh
                        sensoryServiceAppVersion: 1.0.0.0
                        windowsOSVersion: 1.0.0.0
                      status: Success
                type: array
                title: device
      operationId: get_device_information
      description: Get Device Information
  /api/drive/track:
    post:
      x-openapi-router-controller: api
      summary: Drive Track
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                items:
                  type: object
                  properties:
                    result:
                      type: boolean
                    status:
                      type: string
                description: response
                x-examples:
                  example-1:
                    - result: true
                      status: Success
                type: array
                title: response
      parameters:
        - schema: {}
          in: query
          name: RightTrackSpeed
        - schema: {}
          in: query
          name: LeftTrackSpeed
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                RightTrackSpeed: {}
                LeftTrackSpeed: {}
            examples:
              example-1:
                value:
                  LeftTrackSpeed: 30
                  RightTrackSpeed: 70
        description: Drive Track
      operationId: drive_track
      description: Drive Track
  /api/drive/hdt:
    post:
      summary: Drive Heading
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: response
                type: array
                x-examples:
                  example-1:
                    - result: true
                      status: Success
                description: response
                items:
                  type: object
                  properties:
                    result:
                      type: boolean
                    status:
                      type: string
      description: Drive Heading
      operationId: drive_heading
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                Heading: {}
                Distance: {}
                TimeMS: {}
            examples:
              example-1:
                value:
                  Heading: 90
                  Distance: 1
                  TimeMs: 4000
        description: Drive Heading
      x-openapi-router-controller: api
      parameters:
        - schema: {}
          in: query
          name: Heading
        - schema: {}
          in: query
          name: Distance
        - schema: {}
          in: query
          name: TimeMS
  /api/drive/time:
    post:
      summary: Drive Time
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                items:
                  type: object
                  properties:
                    result:
                      type: boolean
                    status:
                      type: string
                description: response
                x-examples:
                  example-1:
                    - result: true
                      status: Success
                type: array
                title: response
      description: Drive Time
      operationId: drive_time
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                LinearVelocity: {}
                AngularVelocity: {}
                TimeMS: {}
            examples:
              example-1:
                value:
                  LinearVelocity: 1
                  AngularVelocity: 4
                  TimeMS: 500
        description: Drive Time
      x-openapi-router-controller: api
      parameters:
        - schema: {}
          in: query
          name: LinearVelocity
        - schema: {}
          in: query
          name: AngularVelocity
        - schema: {}
          in: query
          name: TimeMS
components:
  schemas:
    response:
      title: response
      type: array
      x-examples:
        example-1:
          - result: true
            status: Success
      description: response
      items:
        type: object
        properties:
          result:
            type: boolean
          status:
            type: string
    device:
      title: device
      type: array
      x-examples:
        get-device-information-example:
          - result:
              robotId: '12345'
              serialNumber: '12345'
              batteryLevel: 0.5
              hardwareInfo: {}
              ipAddress: 0.0.0.0
              occipitalDeviceInfo: {}
              outputCapabilities:
                - sure
              robotVersion: 1.0.0.0
              sensorCapabilities:
                - uh hunh
              sensoryServiceAppVersion: 1.0.0.0
              windowsOSVersion: 1.0.0.0
            status: Success
      description: device
      items:
        type: object
        properties:
          result:
            type: object
            properties:
              robotId: {}
              serialNumber: {}
              currentProfileName: {}
              hardwareInfo:
                type: object
              ipAddress: {}
              batteryLevel: {}
              occipitalDeviceInfo:
                type: object
              outputCapabilities:
                type: array
                items: {}
              robotVersion: {}
              sensoryServiceAppVersion: {}
              windowsOSVersion: {}
              sensorCapabilities:
                type: array
                items: {}
          status: {}