openapi: 3.0.0
info:
  title: Misty API
  version: '1.0'
  description: Misty Open API
servers:
  - url: 'http://localhost:3000'
    description: misty
paths:
  /api/drive:
    get:
      x-openapi-router-controller: api
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: response
                type: array
                x-examples:
                  example-1:
                    - result: true
                      status: Success
                description: response
                items:
                  type: object
                  properties:
                    result:
                      type: boolean
                    status:
                      type: string
      requestBody:
        description: ''
        content:
          application/json:
            schema: {}
      parameters:
        - schema:
            type: number
          in: query
          name: AngularVelocity
        - schema:
            type: number
          in: query
          name: LinearVelocity
      description: Drive
      operationId: drive_get
    post:
      x-openapi-router-controller: api
      summary: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: response
                type: array
                x-examples:
                  example-1:
                    - result: true
                      status: Success
                description: response
                items:
                  type: object
                  properties:
                    result:
                      type: boolean
                    status:
                      type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                LinearVelocity:
                  type: number
                AngularVelocity:
                  type: number
            examples:
              example-1:
                value:
                  LinearVelocity: 5
                  AngularVelocity: 5
      description: Drive
      operationId: drive
    parameters: []
  /api/drive/stop:
    get:
      x-openapi-router-controller: api
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: response
                type: array
                x-examples:
                  example-1:
                    - result: true
                      status: Success
                description: response
                items:
                  type: object
                  properties:
                    result:
                      type: boolean
                    status:
                      type: string
      description: Stop
      operationId: stop_get
    post:
      x-openapi-router-controller: api
      summary: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: response
                type: array
                x-examples:
                  example-1:
                    - result: true
                      status: Success
                description: response
                items:
                  type: object
                  properties:
                    result:
                      type: boolean
                    status:
                      type: string
      description: Stop
      operationId: stop
  /api/device:
    get:
      x-openapi-router-controller: api
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: device
                type: array
                x-examples: {}
                items:
                  type: object
                  properties:
                    robotId:
                      type: string
                    serialNumber:
                      type: string
      operationId: get_device_information
      description: Get Device Information
  /api/drive/track:
    get:
      x-openapi-router-controller: api
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: response
                type: array
                x-examples:
                  example-1:
                    - result: true
                      status: Success
                description: response
                items:
                  type: object
                  properties:
                    result:
                      type: boolean
                    status:
                      type: string
      description: Drive Track
      operationId: drive_track_get
      parameters:
        - schema:
            type: string
          in: query
          name: LeftTrackSpeed
        - schema:
            type: string
          in: query
          name: RightTrackSpeed
      requestBody:
        content:
          application/json:
            schema: {}
    post:
      x-openapi-router-controller: api
      summary: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: response
                type: array
                x-examples:
                  example-1:
                    - result: true
                      status: Success
                description: response
                items:
                  type: object
                  properties:
                    result:
                      type: boolean
                    status:
                      type: string
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                RightTrackSpeed:
                  type: number
                LeftTrackSpeed:
                  type: number
            examples:
              example-1:
                value:
                  LeftTrackSpeed: 30
                  RightTrackSpeed: 70
      operationId: drive_track
      description: Drive Track
components:
  schemas:
    response:
      title: response
      type: array
      x-examples:
        example-1:
          - result: true
            status: Success
      description: response
      items:
        type: object
        properties:
          result:
            type: boolean
          status:
            type: string
    device:
      title: device
      type: array
      x-examples: {}
      items:
        type: object
        properties:
          robotId:
            type: string
          serialNumber:
            type: string