openapi: 3.0.0
info:
  title: Misty API
  version: '1.0'
  description: Misty Open API
servers:
  - url: 'http://localhost:3000'
paths:
  /api/drive:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: response
                type: array
                x-examples:
                  example-1:
                    - result: true
                      status: Success
                description: response
                items:
                  type: object
                  properties:
                    result:
                      type: boolean
                    status:
                      type: string
              examples: {}
            application/xml:
              schema:
                type: object
                properties: {}
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              type: 'null'
      parameters:
        - schema:
            type: number
          in: query
          name: AngularVelocity
        - schema:
            type: number
          in: query
          name: LinearVelocity
      description: Drive
      operationId: api.drive_get
    post:
      summary: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: response
                type: array
                x-examples:
                  example-1:
                    - result: true
                      status: Success
                description: response
                items:
                  type: object
                  properties:
                    result:
                      type: boolean
                    status:
                      type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                LinearVelocity:
                  type: number
                AngularVelocity:
                  type: number
            examples:
              example-1:
                value:
                  LinearVelocity: 5
                  AngularVelocity: 5
      description: Drive
      operationId: api.drive_post
    parameters: []
  /api/drive/stop:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: response
                type: array
                x-examples:
                  example-1:
                    - result: true
                      status: Success
                description: response
                items:
                  type: object
                  properties:
                    result:
                      type: boolean
                    status:
                      type: string
      description: Stop
      operationId: api.drive_stop_get
    post:
      summary: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: response
                type: array
                x-examples:
                  example-1:
                    - result: true
                      status: Success
                description: response
                items:
                  type: object
                  properties:
                    result:
                      type: boolean
                    status:
                      type: string
      description: Stop
      operationId: api.drive_stop_post
  /api/device:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: device
                type: array
                x-examples: {}
                items:
                  type: object
                  properties:
                    robotId:
                      type: string
                    serialNumber:
                      type: string
      operationId: api.device_get
      description: Get Device Information
components:
  schemas:
    response:
      title: response
      type: array
      x-examples:
        example-1:
          - result: true
            status: Success
      description: response
      items:
        type: object
        properties:
          result:
            type: boolean
          status:
            type: string
    device:
      title: device
      type: array
      x-examples: {}
      items:
        type: object
        properties:
          robotId:
            type: string
          serialNumber:
            type: string