/* 
 * Misty API
 *
 * Misty Open API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing ApiDeviceResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApiDeviceResultTests
    {
        // TODO uncomment below to declare an instance variable for ApiDeviceResult
        //private ApiDeviceResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ApiDeviceResult
            //instance = new ApiDeviceResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApiDeviceResult
        /// </summary>
        [Test]
        public void ApiDeviceResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ApiDeviceResult
            //Assert.IsInstanceOf(typeof(ApiDeviceResult), instance);
        }


        /// <summary>
        /// Test the property 'RobotId'
        /// </summary>
        [Test]
        public void RobotIdTest()
        {
            // TODO unit test for the property 'RobotId'
        }
        /// <summary>
        /// Test the property 'SerialNumber'
        /// </summary>
        [Test]
        public void SerialNumberTest()
        {
            // TODO unit test for the property 'SerialNumber'
        }
        /// <summary>
        /// Test the property 'CurrentProfileName'
        /// </summary>
        [Test]
        public void CurrentProfileNameTest()
        {
            // TODO unit test for the property 'CurrentProfileName'
        }
        /// <summary>
        /// Test the property 'HardwareInfo'
        /// </summary>
        [Test]
        public void HardwareInfoTest()
        {
            // TODO unit test for the property 'HardwareInfo'
        }
        /// <summary>
        /// Test the property 'IpAddress'
        /// </summary>
        [Test]
        public void IpAddressTest()
        {
            // TODO unit test for the property 'IpAddress'
        }
        /// <summary>
        /// Test the property 'BatteryLevel'
        /// </summary>
        [Test]
        public void BatteryLevelTest()
        {
            // TODO unit test for the property 'BatteryLevel'
        }
        /// <summary>
        /// Test the property 'OccipitalDeviceInfo'
        /// </summary>
        [Test]
        public void OccipitalDeviceInfoTest()
        {
            // TODO unit test for the property 'OccipitalDeviceInfo'
        }
        /// <summary>
        /// Test the property 'OutputCapabilities'
        /// </summary>
        [Test]
        public void OutputCapabilitiesTest()
        {
            // TODO unit test for the property 'OutputCapabilities'
        }
        /// <summary>
        /// Test the property 'RobotVersion'
        /// </summary>
        [Test]
        public void RobotVersionTest()
        {
            // TODO unit test for the property 'RobotVersion'
        }
        /// <summary>
        /// Test the property 'SensoryServiceAppVersion'
        /// </summary>
        [Test]
        public void SensoryServiceAppVersionTest()
        {
            // TODO unit test for the property 'SensoryServiceAppVersion'
        }
        /// <summary>
        /// Test the property 'WindowsOSVersion'
        /// </summary>
        [Test]
        public void WindowsOSVersionTest()
        {
            // TODO unit test for the property 'WindowsOSVersion'
        }
        /// <summary>
        /// Test the property 'SensorCapabilities'
        /// </summary>
        [Test]
        public void SensorCapabilitiesTest()
        {
            // TODO unit test for the property 'SensorCapabilities'
        }

    }

}
