/* 
 * Misty API
 *
 * Misty Open API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing InlineObject2
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineObject2Tests
    {
        // TODO uncomment below to declare an instance variable for InlineObject2
        //private InlineObject2 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineObject2
            //instance = new InlineObject2();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineObject2
        /// </summary>
        [Test]
        public void InlineObject2InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" InlineObject2
            //Assert.IsInstanceOf(typeof(InlineObject2), instance);
        }


        /// <summary>
        /// Test the property 'Heading'
        /// </summary>
        [Test]
        public void HeadingTest()
        {
            // TODO unit test for the property 'Heading'
        }
        /// <summary>
        /// Test the property 'Distance'
        /// </summary>
        [Test]
        public void DistanceTest()
        {
            // TODO unit test for the property 'Distance'
        }
        /// <summary>
        /// Test the property 'TimeMS'
        /// </summary>
        [Test]
        public void TimeMSTest()
        {
            // TODO unit test for the property 'TimeMS'
        }

    }

}
