/* 
 * Misty API
 *
 * Misty Open API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// InlineObject
    /// </summary>
    [DataContract]
    public partial class InlineObject :  IEquatable<InlineObject>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineObject" /> class.
        /// </summary>
        /// <param name="linearVelocity">linearVelocity.</param>
        /// <param name="angularVelocity">angularVelocity.</param>
        public InlineObject(Object linearVelocity = default(Object), Object angularVelocity = default(Object))
        {
            this.LinearVelocity = linearVelocity;
            this.AngularVelocity = angularVelocity;
        }
        
        /// <summary>
        /// Gets or Sets LinearVelocity
        /// </summary>
        [DataMember(Name="LinearVelocity", EmitDefaultValue=false)]
        public Object LinearVelocity { get; set; }

        /// <summary>
        /// Gets or Sets AngularVelocity
        /// </summary>
        [DataMember(Name="AngularVelocity", EmitDefaultValue=false)]
        public Object AngularVelocity { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineObject {\n");
            sb.Append("  LinearVelocity: ").Append(LinearVelocity).Append("\n");
            sb.Append("  AngularVelocity: ").Append(AngularVelocity).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InlineObject);
        }

        /// <summary>
        /// Returns true if InlineObject instances are equal
        /// </summary>
        /// <param name="input">Instance of InlineObject to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineObject input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.LinearVelocity == input.LinearVelocity ||
                    (this.LinearVelocity != null &&
                    this.LinearVelocity.Equals(input.LinearVelocity))
                ) && 
                (
                    this.AngularVelocity == input.AngularVelocity ||
                    (this.AngularVelocity != null &&
                    this.AngularVelocity.Equals(input.AngularVelocity))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.LinearVelocity != null)
                    hashCode = hashCode * 59 + this.LinearVelocity.GetHashCode();
                if (this.AngularVelocity != null)
                    hashCode = hashCode * 59 + this.AngularVelocity.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
